# exec(open('zentao_noctool_kaidan.py').read())
exec(open('aliyun.py').read())
exec(open('tencent.py').read())
exec(open('huawei.py').read())
exec(open('ucloud.py').read())
exec(open('gname_juming_7211_com.py').read())
exec(open('zentaowater.py').read())
exec(open('noctoolwater.py').read())